basePath: /
consumes:
- application/json
definitions:
  data.Product:
    description: defines the structure for an API product
    properties:
      description:
        type: string
      id:
        description: The ID for this product
        minimum: 1
        type: integer
      name:
        type: string
      price:
        type: number
      sku:
        type: string
    required:
    - id
    - name
    - sku
    type: object
  handlers.GenericError:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: Documentation for Product API
  title: of Product API
  version: 1.0.0
paths:
  /:
    get:
      description: returns the products from the data store
      responses:
        "200":
          description: a list of products in the response
          schema:
            items:
              $ref: '#/definitions/data.Product'
            type: array
        "500":
          description: Unable to marshal JSON
      summary: List Products
      tags:
      - products
    post:
      description: Add a new product to the data store
      responses:
        "200":
          description: The newly created product
          schema:
            $ref: '#/definitions/data.Product'
      summary: Create Product
      tags:
      - products
  /:id:
    get:
      description: returns a product with the given ID from the data store
      produces:
      - application/json
      responses:
        "200":
          description: A Product in the response
          schema:
            $ref: '#/definitions/data.Product'
        "404":
          description: Product not found
      summary: List Single Product
      tags:
      - products
    put:
      description: Update a product
      responses:
        "200":
          description: Product after update
          schema:
            $ref: '#/definitions/data.Product'
        "404":
          description: Product not found
        "500":
          description: Product not found
      summary: Update Product
      tags:
      - products
  /{id}:
    delete:
      description: deletes a product from the data store
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.GenericError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.GenericError'
      summary: Delete Product
      tags:
      - products
produces:
- application/json
schemes:
- http
swagger: "2.0"
